name: PokeColorNick
main: pokemon.Main
version: 1.3
author: Xyue_dada
api-version: 1.12.2
commands:
    pnick:
        aliases:
            - pcn
            - pokecn
            - pokecolornick
permissions:
    Pnick.op:
        default: op
        description: "OP"
